global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: scylla
  static_configs:
    - targets:
      - scylla:9180
- job_name: redis
  static_configs:
    - targets:
      - redis-exporter:9121
- job_name: rabbitmq
  static_configs:
    - targets:
      - rabbitmq:15692
